### ISSUE TITLE
Cannot read property 'bool' of undefined at react.proptypes.bool of react-bottomsheet.js file

### ISSUE THREAD

**Issue by ajeshb** [bellaChoi/react-bottomsheet#2]
I am using react version 16.2.0. When I try to import ReactBottomsheet, I get this error. @bellaChoi @ignocide

**Comment by bellaChoi** [comment]
Fixed an issue where PropTypes could not be loaded in React-15.5.4 or later (added 'prop-types' module). @ajeshb
